### ISSUE TITLE
VobSub2SRT fails to build with tesseract 3.02

### ISSUE THREAD

**Issue by ruediger** [ruediger/VobSub2SRT#19]
Reported by e-mail:

This seems to be the core of it

```
In file included from
/home/ozone/subchain/usr/include/tesseract/apitypes.h:23:0,
                 from
/home/ozone/subchain/usr/include/tesseract/baseapi.h:28,
                 from /home/ozone/subchain/VobSub2SRT/src/vobsub2srt.c++:27:
/home/ozone/subchain/usr/include/tesseract/publictypes.h:108:28: error:
comma at end of enumerator list [-pedantic]
/home/ozone/subchain/usr/include/tesseract/publictypes.h:122:38: error:
comma at end of enumerator list [-pedantic]
/home/ozone/subchain/usr/include/tesseract/publictypes.h:139:35: error:
comma at end of enumerator list [-pedantic]
/home/ozone/subchain/usr/include/tesseract/publictypes.h:221:22: error:
comma at end of enumerator list [-pedantic]
In file included from
/home/ozone/subchain/usr/include/tesseract/baseapi.h:30:0,
                 from /home/ozone/subchain/VobSub2SRT/src/vobsub2srt.c++:27:
/home/ozone/subchain/usr/include/tesseract/unichar.h:42:14: error: comma
at end of enumerator list [-pedantic]
In file included from
/home/ozone/subchain/usr/include/tesseract/tesscallback.h:22:0,
                 from
/home/ozone/subchain/usr/include/tesseract/baseapi.h:31,
                 from /home/ozone/subchain/VobSub2SRT/src/vobsub2srt.c++:27:
/home/ozone/subchain/usr/include/tesseract/host.h:108:1: error: ISO C++
1998 does not support ‘long long’ [-Wlong-long]
/home/ozone/subchain/usr/include/tesseract/host.h:109:1: error: ISO C++
1998 does not support ‘long long’ [-Wlong-long]
In file included from
/home/ozone/subchain/usr/include/tesseract/unicharset.h:23:0,
                 from
/home/ozone/subchain/usr/include/tesseract/ltrresultiterator.h:26,
                 from
/home/ozone/subchain/usr/include/tesseract/resultiterator.h:26,
                 from
/home/ozone/subchain/usr/include/tesseract/baseapi.h:34,
                 from /home/ozone/subchain/VobSub2SRT/src/vobsub2srt.c++:27:
/home/ozone/subchain/usr/include/tesseract/errcode.h:98:2: error: extra
‘;’ [-pedantic]
In file included from
/home/ozone/subchain/usr/include/tesseract/ltrresultiterator.h:26:0,
                 from
/home/ozone/subchain/usr/include/tesseract/resultiterator.h:26,
                 from
/home/ozone/subchain/usr/include/tesseract/baseapi.h:34,
                 from /home/ozone/subchain/VobSub2SRT/src/vobsub2srt.c++:27:
/home/ozone/subchain/usr/include/tesseract/unicharset.h:165:66: warning:
type qualifiers ignored on function return type [-Wignored-qualifiers]
/home/ozone/subchain/usr/include/tesseract/unicharset.h:170:46: warning:
type qualifiers ignored on function return type [-Wignored-qualifiers]
/home/ozone/subchain/usr/include/tesseract/unicharset.h:185:50: warning:
type qualifiers ignored on function return type [-Wignored-qualifiers]
/home/ozone/subchain/usr/include/tesseract/unicharset.h:191:54: warning:
type qualifiers ignored on function return type [-Wignored-qualifiers]
In file included from
/home/ozone/subchain/VobSub2SRT/src/vobsub2srt.c++:27:0:
/home/ozone/subchain/usr/include/tesseract/baseapi.h:653:32: warning:
type qualifiers ignored on function return type [-Wignored-qualifiers]
/home/ozone/subchain/usr/include/tesseract/baseapi.h:657:29: warning:
type qualifiers ignored on function return type [-Wignored-qualifiers]
/home/ozone/subchain/VobSub2SRT/src/vobsub2srt.c++: In function ‘int
main(int, char**)’:
```

Changing CXXFLAGS from -pedantic-errors to -pedantic (and adding -Wno-long-long) should fix this.

This seems to actually be a bug in tesseract if they want C++98 compliance. C++11 allows comma at end of enumerator list. TODO: Report upstream?
